# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaabb6377e968f237ddf25a6d995828c793f40c5e8f51d18498ec556dbbadaef00f9078aa41318aae45394aa0f3712863021c12ef5eca585ca8c5687be24eb6c

test:
  secret_key_base: a191e542ce7d622d202454e9e102703d8f7079ad990a471971557f3038dcdc601091430378342a5ca6347361e264be26fe58b0e28f0b87e0c94fae11a15c25e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
